[libraries]
classgraph = "io.github.classgraph:classgraph:4.8.160"
jackson-annotations = "com.fasterxml.jackson.core:jackson-annotations:2.15.2"
jsr305 = "com.google.code.findbugs:jsr305:3.0.2"
junit-jupiter = "org.junit.jupiter:junit-jupiter:5.9.3"
kotlin-reflect = "org.jetbrains.kotlin:kotlin-reflect:1.8.21"
