name: FHIR R4 Models Tests
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: oci-shared

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradlew Test
        run: ./gradlew test

      - name: Gradlew Test Events
        run: ./gradlew testEvents
